name: Deploy to AWS Lambda

on:
  push:
    branches: [ "main" ]

permissions: {}

jobs:
  deploy:
    name: Update functions
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install Rust and Cargo Lambda
      uses: moonrepo/setup-rust@v1
      with:
        bins: cargo-lambda

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0

    - name: Build
      run: |
        cargo lambda build \
          --release \
          --arm64

        mkdir -p deploy

        cp \
          target/lambda/svg-proxy-lambda/bootstrap \
          deploy/bootstrap

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_LAMBDA_REGION }}
        role-to-assume: ${{ secrets.AWS_LAMBDA_DEPLOY_ROLE_ARN }}
        role-session-name: lambda-deploy

    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: svg-proxy
        code-artifacts-dir: deploy
        handler: main.handler
        runtime: provided.al2023 # Amazon Linux 2023
        architectures: arm64
